FS-Driverless/Formula-Student-Driverless-Simulator

.github/workflows/main.yml
Simulator/src/airsim_ros_interface/CMakeLists.txt
Simulator/src/airsim_ros_interface/include/airsim_ros_wrapper.h
Simulator/src/airsim_ros_interface/launch/rviz.launch

This PR adds basic CI to the project by setting up a correct environment for the project and building the catkin workspace as only test. This can easily be extended to accommodate more jobs and tests.
@SijmenHuizenga I would appreciate if you could have a look at why the build is currently failing (I think it has to do with how I am setting up the environment currently).

Github Actions for ROS workspace

---

docs/get-ready-to-develop.md

These were found when setting up github actions.

add additional dependencies to docs

---

ros/src/examples/CMakeLists.txt
ros/src/examples/README.md
ros/src/examples/launch/sinewave.launch
ros/src/examples/package.xml
ros/src/examples/scripts/sinewave.py

Adds the example package with a sinewave publishers. This package will be super usefull for teams to learn how to integrate their autonomous system with FSDS.

Sinewave autonomous system example

---

ros/src/examples/CMakeLists.txt
ros/src/examples/README.md
ros/src/examples/launch/sinewave.launch
ros/src/examples/package.xml
ros/src/examples/scripts/sinewave.py

Pr #42 got merged into the wrong branch :sweat_smile: so let's just now merge it into master

Implemented example sinewave

---

ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp

set a lower bound of 0 for braking and throttle commands

---

.gitignore
README.md
build_docs.sh
docs/how-to-develop.md
docs/how-to-simulate.md
docs/integration-handbook.md
docs/joystick.md
docs/ros-bridge.md
docs/statistics.md
mkdocs.yml
ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp

https://fs-online.github.io/Driverless-Competition-Simulator/

Add github pages documentation website

---

docs/README.md

small addition. Let me know if you prefer the picture to be placed at the bottom of the text

add pretty picture to landing page top

---

ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp

Required for multi-node bridging. It also fixes duration out of bound error

Direct translation between unreal and ros timestamps. 

---

UE4Project/Source/Blocks.Target.cs
UE4Project/Source/BlocksEditor.Target.cs

Fixes this problem:
[Solution provided by this Samaritan](https://forums.unrealengine.com/development-discussion/c-gameplay-programming/1770131-solved-upgrade-c-project-from-ue-4-24-to-4-25-under-linux#post1770635)

Upgrade to UE Build settings V2 to support UE4.25 on Ubuntu.

---

ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp

Fix bug where imu data is always 0

---

UE4Project/Content/RaceCourse/Maps/IM_MAP1.umap
UE4Project/Content/RaceCourse/Model/Splines/spline_cones.uasset
UE4Project/Content/blueprint/RefereeBlueprint.uasset

Fix Unreal Training Map contains 19296 cones

---

docs/how-to-simulate.md

Document how to clone using http

---

UE4Project/Plugins/AirSim/Content/AirsimSpectatorPawn.uasset
UE4Project/Plugins/AirSim/Content/AirsimSpectatorTeleportTrigger.uasset
docs/spectator.md

closes #123 
Demo video: https://www.youtube.com/watch?v=0YozSnwiImE

Add spectator car following and teleportation based on car's progress

---

docs/ros-bridge.md
ros/src/fsds_ros_bridge/config/multiplot/multiplot.xml
ros/src/fsds_ros_bridge/launch/fsds_ros_bridge.launch
ros/src/fsds_ros_bridge/rviz/default.rviz

Added the option of launching multiplot and/or rviz when launching the bridge and updated the multiplot and rviz config files with the updated topic names.

Update Rviz and Multiplot helpers

---

ros/src/fsds_ros_bridge/launch/fsds_ros_bridge.launch

These typos were the result of #152

Fix typos in launchfile

---

docs/getting-started.md

fix link in getting-started.md

---

docs/getting-started.md
docs/software-install-instructions.md
ros/src/fsds_ros_bridge/launch/fsds_ros_bridge.launch
ros/src/fsds_ros_bridge/scripts/cameralauncher.py

Zalán from FRT has been doing some testing, this pr contains some of the things they ran into.

Docs improvements

---

UE4Project/Plugins/AirSim/Source/Vehicles/Car/CarPawnSimApi.h

Remove duplicate typedef.
Fixes https://github.com/FS-Online/Formula-Student-Driverless-Simulator/issues/193

fix duplicate typedef

---

README.md

In #180 we concluded to use jitter as chat place. This pr adds the link.

Added link to Jitter chatt

---

.gitmodules
README.md
UE4Project/Config/DefaultGame.ini
config/team_config.json
docs/getting-started.md
docs/joystick.md
docs/operator.md
docs/ros-bridge.md
docs/software-install-instructions.md
docs/vehicle_model.md
mkdocs.yml
settings.json

Elaborated the docs on Ubuntu setup (added a few more fine-grained steps and troubleshooting) and corrected the name of the Github organization

Ubuntu docs

---

AirSim/AirLib/src/api/RpcLibClientBase.cpp
ros/src/fsds_ros_bridge/include/statistics.h
ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp
ros/src/fsds_ros_bridge/src/fsds_ros_bridge_camera.cpp
ros2/src/fsds_ros2_bridge/include/statistics.h
ros2/src/fsds_ros2_bridge/src/airsim_ros_wrapper.cpp
ros2/src/fsds_ros2_bridge/src/fsds_ros2_bridge_camera.cpp

This is a ROS best practice, and it has multiple benefits, including:
- Logs are saved to files by default
- Logs can be filtered using RQT
- Nice colours in terminal

Improve logging by using dedicated rclcpp methods instead of cout

---

ros2/src/fsds_ros2_bridge/src/fsds_ros2_bridge.cpp

Read host parameter correctly in ROS2 bridge

---

AirSim/AirLib/src/api/RpcLibServerBase.cpp
UE4Project/FSOnline.uproject
UE4Project/Plugins/AirSim/Source/AirSim.Build.cs
docs/software-install-instructions.md

Switch to Unreal Engine 4.27

---

UE4Project/Plugins/AirSim/Source/Vehicles/Car/CarPawn.cpp
UE4Project/Plugins/AirSim/Source/Vehicles/Car/CarPawn.h
UE4Project/Plugins/AirSim/Source/Vehicles/Car/CarPawnSimApi.cpp
UE4Project/Plugins/AirSim/Source/Vehicles/Car/CarPawnSimApi.h
UE4Project/Plugins/AirSim/Source/Vehicles/Car/SimModeCar.cpp

This PR removes some old unnecessary code cluttering the codebase

Remove unnecessary code

---

docs/custom-mapping.md

Parameter was not yet changed in the docs

Correct parameter for custom map loading

---

AirSim/PythonClient/airsim/client.py
operator/operator.py
operator/requirements.txt

Make some changes to make the operator run again

Fix operator

---

UE4Project/Config/DefaultGame.ini
docker/download_FSDSSimulator_binary.sh
docs/docker_ubuntu.md
docs/getting-started-with-ros.md

This pull request will get all the docs ready for release v2.2.0

Release v2.2.0

---

docs/getting-started-with-ros.md
docs/software-install-instructions.md

Adds the official documentation.

Change installation for GUI Support
