FS-Driverless/Formula-Student-Driverless-Simulator

AirSim/AirLib/include/common/AirSimSettings.hpp, AirSim/AirLib/include/sensors/lidar/LidarSimpleParams.hpp, UE4Project/Plugins/AirSim/Settings/settings.json, UE4Project/Plugins/AirSim/Source/SimMode/SimModeBase.cpp, UE4Project/Plugins/AirSim/Source/UnrealSensors/UnrealLidarSensor.cpp, docs/ros-bridge.md, ros/src/fsds_ros_bridge/include/airsim_ros_wrapper.h, ros/src/fsds_ros_bridge/launch/static_transforms.launch, ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp
In this pr all transforms, data frames and coordinate systems are configured to work like a real car. Large changes are:
1. For lidar, hard-code the dataframe of the points to the sensor frame. All lidar points should always be relative to the actual sensor.
2. For camera's, only publish the static transform between sensor body and center of the car. All other transforms have been removed.
3. Do not publish transforms between the car's location and the world. Using this data the ground truth of the car could be found which would defeat part of the challenge.
4. Prefixed all frames with `fsds/` to prevent collisions with existing frames.
5. Hard-coded the primary vehicle frame to FSCar.
=> Real life transforms

AirSim/AirLib/include/api/RpcLibAdapatorsBase.hpp, AirSim/AirLib/include/sensors/imu/ImuBase.hpp, AirSim/AirLib/include/sensors/imu/ImuSimple.hpp, AirSim/AirLib/src/api/RpcLibServerBase.cpp, ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp
#130 
Fixes and populates the of IMU's gyro and accelerometer variances. Also includes the accumulating bias error - depending on performance, a revision potentially required to only account for the Gaussian noise part within covariance matrices of gyro and acce
=> Adding gyro and accelerometer variances to IMU output message

ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp
Similar to how the IMU message is attached to the frame of the car, the GPS should also contain the frame of the car. This is something that was useful to have when implementing an EKF for the MITeamDelft state estimation system.
=> added frame to GPS ROS message

AirSim/AirLib/include/common/AirSimSettings.hpp, AirSim/AirLib/include/sensors/lidar/LidarSimple.hpp, AirSim/AirLib/include/sensors/lidar/LidarSimpleParams.hpp, UE4Project/Plugins/AirSim/Source/SimMode/SimModeBase.cpp, UE4Project/Plugins/AirSim/Source/SimMode/SimModeBase.h, UE4Project/Plugins/AirSim/Source/UnrealSensors/UnrealLidarSensor.cpp, UE4Project/Plugins/AirSim/Source/UnrealSensors/UnrealLidarSensor.h, config/team_config.json, docs/integration-handbook.md, docs/lidar.md, ros/src/fsds_ros_bridge/include/airsim_ros_wrapper.h, ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp, settings.json
* Added more lidar rules as proposed in #127 to prevent unrealistic setups
* Simplify lidar capture model to ease configuration
* split documentation into 'lidar configuration' (see lidar.md) and 'competition rules' (see integration-handbook.md). Should solve #132 
* Fixed bug in lidar debug points where all points where mirrored because ned vs enu frame.
* Renamed setting `NumberOfChannels` to `NumberOfLasers`
* Renamed setting `PointsPerSecond` to `PointsPerScan`
* Removed `startup_delay` configuration as it must always be 0
* Changed the lidar simulation to always do 1 full 360 capture during every update. Before, the time-diff was used to calculate how much the lidar had rotated and capture based on this. This resulted in unexpected behavior when small lag happens causing no points to …
=> Lidar realistic rules, simplify capture configuration and improved documentation.

docs/camera.md, docs/integration-handbook.md, docs/lidar.md, mkdocs.yml, ros/src/fsds_ros_bridge/scripts/cameralauncher.py, ros/src/fsds_ros_bridge/src/fsds_ros_bridge_camera.cpp, settings.json
This pr adds depth camera's. Read the docs on a description of how they work.
=> Depth cameras

AirSim/AirLib/include/sensors/imu/ImuSimple.hpp, docs/ros-bridge.md, ros/src/examples/scripts/sinewave.py, ros/src/fsds_ros_bridge/launch/fsds_ros_bridge.launch, ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp
* Add 'manual_mode' in rosbridge that toggles api controll. This was needed because previously competition_mode enabled/disabled api control which caused the car to be not drivable in non-competition mode
* Fix bug where IMU linear acceleration was going exponentially high
* Fix sinewave.py message reference
=> Hotfixes before v1.0.0 release

UE4Project/Content/RaceCourse/Model/Splines/spline_cones.uasset
=> Enable CCD on cones to prevent cones falling though world.

docs/ros-bridge.md, ros/src/fsds_ros_bridge/CMakeLists.txt, ros/src/fsds_ros_bridge/include/airsim_ros_wrapper.h, ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp, ros/src/fsds_ros_bridge/srv/Reset.srv
I have not renamed fs_msgs! fs_msgs now contains a service as well, however renaming would be a breaking change. I think we can stick with fs_msgs for now, maybe there is a better opportunity to rename it later on.
Fixes #251
=> Moved /fsds/reset to fs_msgs

UE4Project/Content/FormulaStudentAssets/RefereeBP.uasset, UE4Project/Content/FormulaStudentAssets/StartFinishLine.uasset, UE4Project/Plugins/AirSim/Source/Referee.cpp, UE4Project/Plugins/AirSim/Source/Referee.h
This is a solution for issue #254.
Probably not the cleanest way to do this, but I don't know much about unreal engine. Wanted to the same thing in the referee blueprint as was done with 'Track', but for some reason my reference to the start finish line never became anything else than 'None'.
=> Added big orange cones to testing_only track

ros2/src/fsds_ros2_bridge/include/airsim_ros_wrapper.h, ros2/src/fsds_ros2_bridge/src/airsim_ros_wrapper.cpp
=> Fix wrong twist in odometry messages

UE4Project/Plugins/AirSim/Source/AirBlueprintLib.cpp, UE4Project/Plugins/AirSim/Source/AirSim.Build.cs
This fixes the 
- ```WARNING: Library ‘stdc++’ was not resolvable to a file when used in Module ‘AirSim’, assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use Public System Library Paths if you do intended to use this slow path to suppress this warning.``` warning by removing the unneeded dependency declarations on `stdc++` and `supc++`,
- ```RenderData is deprecated. Please use GetRenderData() instead``` warning by doing what it says to do.
I've verified that the project still compiles and packages succesfully on linux, and it certainly does too on windows
=> Fix linux compilation warnings

AirSim/AirLib/include/common/Settings.hpp, AirSim/AirLib/include/common/common_utils/FileSystem.hpp, UE4Project/Plugins/AirSim/Source/AirSim.Build.cs, UE4Project/Plugins/AirSim/Source/AirSimGameMode.cpp, UE4Project/Plugins/AirSim/Source/AirSimGameMode.h, docs/getting-started.md
Add abilities to load settings.json from 
- the same folder the game binary is in, 
- the current working directory from which the binary is launched
- a path specified by the `-settings "<absolute path to a settings.json file>"` command line argument
- directly from the value of the `-settings "<URL encoded string>"` command line argument, as a URL encoded json string
Closes #309
=> Better settings loading

UE4Project/Plugins/AirSim/Source/Vehicles/Car/CarPawnSimApi.cpp, UE4Project/Plugins/AirSim/Source/Vehicles/Car/CarPawnSimApi.h
Before the code used for rpm calculations took a crude numerical derivative of wheel rotation angle, which was hacky and had potential to fail at higher rpms / lower physics update rates. The new code plugs into the internals of the vehicle simulation to retrieve wheel velocities and angles directly.
=> Improve wheel rpm calculation

ros2/src/fsds_ros2_bridge/include/airsim_ros_wrapper.h, ros2/src/fsds_ros2_bridge/src/airsim_ros_wrapper.cpp
This has been tested on Humble and Galactic in Ubuntu 20.04, WSL2.
These were problematic lines stopping the bridge from `colcon` building in Humble, but maintains backwards compatibility.
As mentioned in https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/issues/296 there may be further compatibility issues with Ubuntu 22.04 that can be addressed in a future PR.
=> ROS2 Humble compatibility

AirSim/AirLib/include/api/RpcLibClientBase.hpp, AirSim/AirLib/include/api/WorldSimApiBase.hpp, AirSim/AirLib/include/common/AirSimSettings.hpp, AirSim/AirLib/src/api/RpcLibClientBase.cpp, AirSim/AirLib/src/api/RpcLibServerBase.cpp, UE4Project/Plugins/AirSim/Source/WorldSimApi.cpp, UE4Project/Plugins/AirSim/Source/WorldSimApi.h, python/fsds/client.py, ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp, ros2/src/fsds_ros2_bridge/src/airsim_ros_wrapper.cpp
Instead of reading the settings.json from a file, the ROS bridge will obtain the settings from AirSim via RPC. This is needed because AirSim no longer looks for settings.json in one place, and possibly reads it from command line, so ROS bridge couldn't access it in any other way.
Closes #308
=> Ros use same settings as airsim

UE4Project/Plugins/AirSim/Source/UnrealSensors/UnrealLidarSensor.cpp
The convention of the vertical FOV was inverted with respect to the [convention in the docs](https://fs-driverless.github.io/Formula-Student-Driverless-Simulator/v2.1.0/coordinate-frames/)
I inverted them in the lidar sensor.
Closes #318
=> Invert vertical_angle for correct convention

AirSim/AirLib/include/api/RpcLibClientBase.hpp, AirSim/AirLib/src/api/RpcLibClientBase.cpp, ros/src/fsds_ros_bridge/include/airsim_ros_wrapper.h, ros/src/fsds_ros_bridge/scripts/cameralauncher.py, ros/src/fsds_ros_bridge/src/airsim_ros_wrapper.cpp, ros/src/fsds_ros_bridge/src/fsds_ros_bridge.cpp, ros/src/fsds_ros_bridge/src/fsds_ros_bridge_camera.cpp, ros2/src/fsds_ros2_bridge/include/airsim_ros_wrapper.h, ros2/src/fsds_ros2_bridge/src/airsim_ros_wrapper.cpp, ros2/src/fsds_ros2_bridge/src/fsds_ros2_bridge.cpp, ros2/src/fsds_ros2_bridge/src/fsds_ros2_bridge_camera.cpp
I've encountered an issue where if the ros bridge and the simulator are launched simultaneously, but the simulator takes longer to load, then ros bridge exits with an error saying that it could not connect. I thought that it would be better to wait a configurable amount of time for the simulator to load, so I've added this to the ROS2 bridge. @wouter-heerwegh, could you copy and test the changes for ROS1? Should be quick, the change is really small.
The ROS parameter `timeout` will control how much time to wait for the RPC server (simulator) to become available
=> Add waiting for RPC server to become available

UE4Project/Plugins/AirSim/Content/VehicleAdv/Cars/AdsDv/AdsDv_Pawn.uasset, UE4Project/Plugins/AirSim/Content/VehicleAdv/Cars/TechnionCar/TechnionCarPawn.uasset
Fixes #334 for both the technion and FSAI vehicle.
I also added a gear ratio of -1 for the FSAI vehicle, as this is nice for debugging. It is not possible to reverse using the python API or ROS bridges.
=> Fix drifting

.gitmodules, ros2/src/fsds_ros2_bridge/CMakeLists.txt
Not sure if this has been affecting ppl but I was resetting some of my branches and this got in the way.
The directory says `external` is within `Airsim` not `Airsim/Airlib`
=> Matching rpclib to repo's directory

ros/src/fsds_ros_bridge/src/fsds_ros_bridge_camera.cpp, ros2/src/fsds_ros2_bridge/src/fsds_ros2_bridge_camera.cpp
=> Change camera prefix to follow documentation and to follow lidar naming convention

.github/workflows/main.yml, AirSim/build.sh, AirSim/setup.sh, ros2/src/fsds_ros2_bridge/CMakeLists.txt, ros2/src/fsds_ros2_bridge/include/airsim_ros_wrapper.h, ros2/src/fsds_ros2_bridge/src/fsds_ros2_bridge_camera.cpp
This PR aims to introduce ROS2 building for Humble and Jazzy.
=> Workflow: Rework and build for ROS2 Humble and Jazzy

docs/ground-speed-sensor.md
The refrence frame of the GSS was changed in #304 from global to local.
This updates the documentation to reflect that.
=> Update documentation for refrence frame of GSS

ros2/src/fsds_ros2_bridge/launch/fsds_ros2_bridge.launch.py, ros2/src/fsds_ros2_bridge/src/airsim_ros_wrapper.cpp
I'm finally porting my personal code to ROS2, I saw that `/fsds/` was never prepended to any topic (while it is in ROS1).
I added the fsds namespace to the bridge node to align with the documentation and ROS1 and also made `testing_only/track` transient local. If your subscriber is also transient local, it should act like a latching topic now. This fixes #367.
=> ROS2 Namespace and testing_only/track latching
